### ISSUE TITLE
Random Crate crash beim rechtsklicken

### ISSUE THREAD

**Issue by DerOli82** [BakermanLP/ProjectRETv10#21]
Crash-Report: https://gist.github.com/DerOli82/5b754798877ce6afef88dc7e6432b121

**Comment by BakermanLP** [comment]
Cross Ref: https://github.com/Zairus/RandomRestockableCrates/issues/1

**Comment by BakermanLP** [comment]
Erst mal raus, da sich hier nichts tut.
