### ISSUE TITLE
Crash bei NeoTech

### ISSUE THREAD

**Issue by Jan-Ellmers** [BakermanLP/ProjectRETv10#32]
Als ich mit NeoTech rumgespielt habe ist mir das Spiel abgeschmiert das ist der Report:

http://pastebin.com/y6cP9swa

Als ich dann die Welt neu laden wollte ist es wieder mit diesem Report abgestürzt:

http://pastebin.com/4yQm93pL

**Comment by BakermanLP** [comment]
Die Pipes müssen so gut gewesen sein, dass diese mit diesem Commit komplett aus dem Mod gelöscht worden sind ?!?!?!
https://github.com/TeamBR-Modding/NeoTech/commit/735d9addbffe01e1d44821b62377228ebca34506
